### ISSUE TITLE
Support Audio via 3.5mm jack

### ISSUE THREAD

**Issue by Nightmare204** [carlonluca/pi#16]
Right now PiOmxTextures plays audio only through HDMI, even if you try to force it via 3.5mm ('headphone') jack configuring it with raspi-config.
It would be nice if the audio output could be selected or followed the configuration of the raspberry.

**Comment by desert** [comment]
Yes, specially since there are some HMDI to VGA converters, and you loose audio.

**Comment by carlonluca** [comment]
What about both?

**Comment by Nightmare204** [comment]
If audio comes out via both (HDMI and Jack) at the same time I don't think that would be a problem.
For those cases where you lose the audio through HDMI because of a converter this could be a solution...

**Comment by carlonluca** [comment]
#4591c30 should solve this issue. Reopen if it is not fixing this.

**Comment by Nightmare204** [comment]
It's working Perfectly... Great work @carlonluca
