### ISSUE TITLE
Position implementation disabled

### ISSUE THREAD

**Issue by Nightmare204** [carlonluca/pi#17]
The position implementation in the No_Tearing branch was disabled because it was hardlocking.
That branch was merged to Master before fixing this bug and so the position is still disabled.

**Comment by carlonluca** [comment]
Fixed. Seems to work now. Reopen if something wrong happens again.

**Comment by Nightmare204** [comment]
Tested.... and now It's working

**Comment by carlonluca** [comment]
Great! Thank you!
Il 06/Apr/2015 23:59, "Nightmare204" <notifications@github.com> ha scritto:
