### ISSUE TITLE
build instructions not working (not possible to build)

### ISSUE THREAD

**Issue by dimovnike** [carlonluca/pi#20]
the build instructions on the blog are not working, i tried different order of operations but still no luck. Any chance something is missing there?

**Comment by dimovnike** [comment]
in the end it built some how, but I don't know what exactly i did. Looks like you need to build qtmultimedia with gstreamer first, then build piomxtextures_qt_driver, make install it, and then patch the qtmuiltimedia, run qmake with -nocache, clean it and rebuild.

**Comment by carlonluca** [comment]
Yes, the qtmultimedia patch tries to build the backend, but this is not the case anymore with the new build procedure. I'll fix that.

**Comment by carlonluca** [comment]
Should be fixed now. Reopen if you still encounter issue while building.
