### ISSUE TITLE
Stop a video, then seek, then crash and other crashes when stopped

### ISSUE THREAD

**Issue by desert** [carlonluca/pi#23]
In the piomxtextures_app if you stop the video, then seek, it crashes. I guess it goes beyond, and applies  to any player doing those commands in that order.

UPDATE:
- The piomxtextures_pocplayer also crashes when hitting play and no video is loaded.

**Comment by atr0n** [comment]
It may be due to openmaxilstreamscontrol is not implemented, right?
Maybe playbackState is not sending playbackStateChanged() signal when the video stops and then, Qt tries to seek on closed file.

**Comment by dimovnike** [comment]
Ah yes, it might be the seek because where i do mute i do seek() too. Will do more tests and get back.

**Comment by dimovnike** [comment]
correction: looks like seek and mute are different bugs, because in one of the tests I only commented mute part in QML and there are no crashes anymore, however after some seek() calls video becomes laggy.

**Comment by carlonluca** [comment]
Seems to be fixed. Can someone double check?

**Comment by carlonluca** [comment]
If you want to also test stability of the seek implementation you can use POCPlayer. I added a --seektest param:

`./piomxtextures_pocplayer --seektest <uri>`

that will perform a never ending seek.

**Comment by carlonluca** [comment]
I stopped the test after 3664 seeks. No issue registered. Seek by itself seems to be ok. Reopen if you still get some crash.
