### ISSUE TITLE
compiling piomxtextures_qt_driver requires super user permissions

### ISSUE THREAD

**Issue by dimovnike** [carlonluca/pi#24]
running make in piomxtextures_qt_driver requires super user permissions, looks like it is doing also make install. Below is the error.

mv -f libopenmaxilmediaplayer.so /usr/local/qt-5.4.1/plugins/mediaservice/ 
mv: inter-device move failed: ‘libopenmaxilmediaplayer.so’ to ‘/usr/local/qt-5.4.1/plugins/mediaservice/libopenmaxilmediaplayer.so’; unable to remove target: Permission denied
Makefile:319: recipe for target '/usr/local/qt-5.4.1/plugins/mediaservice/libopenmaxilmediaplayer.so' failed

**Comment by carlonluca** [comment]
Sufficient to change the permissions of the Qt dir.

**Comment by dimovnike** [comment]
its a bit of security issue  but I'll close it, there are more important bugs now (the one with mute and seek).
