### ISSUE TITLE
Changing Video shows video jump - V5.0.0

### ISSUE THREAD

**Issue by Nightmare204** [carlonluca/pi#30]
I have the following code to change the playing video:

    function changeVideo(path)
    {
        archivo = path
        askedStop = true;
        videoPlayer.stop()
        videoPlayer.source = archivo
        videoPlayer.play()
    }

When the video change a jump back in the video can be seen.
I guess the index of the frame being shown is changed to the first one again, but it is done before cleaning. That for the video jumps back before playing the next source.

**Comment by carlonluca** [comment]
Beta 2 should fix this.
