### ISSUE TITLE
MediaPlayer.loops property now working - V5.5.0

### ISSUE THREAD

**Issue by sinadogru** [carlonluca/pi#32]
When I try to loop a video infinitely, after the first play it just stops and do not replay the video.

If you like to mimic this here is the simple code,

import QtQuick 2.0
import QtMultimedia 5.0
import QtQuick.Window 2.0

Window {
    visible: true

    MediaPlayer {
        id: player
        source: "file:///home/pi/Videos/big_buck_bunny_1080p_h264.mov"
        loops: MediaPlayer.Infinite
    }

    VideoOutput {
        source: player
    }

    Component.onCompleted: {
        player.play();
    }
}

And also here is the debug output, 

stdin: is not a tty
QML debugging is enabled. Only use this in a safe environment.
Unable to query physical screen size, defaulting to 100 dpi.
To override, set QT_QPA_EGLFS_PHYSICAL_WIDTH and QT_QPA_EGLFS_PHYSICAL_HEIGHT (in millimeters).
12:22:53.879 VERBOSE: Instantiating player service...
12:22:53.881 VERBOSE: Instantiating QMediaService...
12:22:53.884 DEBUG: Entering: OpenMAXILPlayerControl::OpenMAXILPlayerControl(QObject*).
12:22:53.885 VERBOSE: Metadata update requested.
12:22:53.887 DEBUG: Entering: virtual void OpenMAXILPlayerControl::setMediaPlayer(QMediaPlayer*).
Requesting control for org.qt-project.qt.metadatareadercontrol/5.0...
Requesting control for org.qt-project.qt.mediaavailabilitycontrol/5.0...
Requesting control for org.qt-project.qt.mediaplayercontrol/5.0...
Requesting control for org.qt-project.qt.medianetworkaccesscontrol/5.0...
12:22:53.888 DEBUG: Entering: virtual QMediaPlayer::State OpenMAXILPlayerControl::state() const.
12:22:53.888 DEBUG: Entering: virtual QMediaPlayer::MediaStatus OpenMAXILPlayerControl::mediaStatus() const.
QDeclarativeAudio::itemChange
QMediaPlayer::onItemChanged
QDeclarativeAudio::itemChange
QMediaPlayer::onItemChanged
12:22:53.896 DEBUG: Entering: virtual void OpenMAXILVideoRendererControl::setSurface(QAbstractVideoSurface*).
12:22:53.897 DEBUG: Entering: virtual void OpenMAXILPlayerControl::stop().
12:22:53.897 VERBOSE: Stop
12:22:53.898 DEBUG: Entering: virtual void OpenMAXILPlayerControl::setMedia(const QMediaContent&, QIODevice*).
12:22:53.898 DEBUG: Media: file:///home/pi/Videos/big_buck_bunny_1080p_h264.mov.
12:22:53.899 DEBUG: setMedia thread is: 0x529758.
12:22:53.899 VERBOSE: Deferring setMedia()...
Requesting control for org.qt-project.qt.videorenderercontrol/5.0...
12:22:53.900 DEBUG: Entering: virtual void OpenMAXILPlayerControl::play().
12:22:53.900 VERBOSE: Deferring play() command...
12:22:53.902 VERBOSE: Processing post setMedia()...
12:22:53.902 DEBUG: Entering: void OpenMAXILPlayerControl::setMediaInt(const QMediaContent&).
12:22:53.902 VERBOSE: Stop
12:22:53.902 VERBOSE: Entering: bool OMX_MediaProcessor::setFilenameInt(QString, OMX_TextureData*&).
12:22:53.902 VERBOSE: Opening file:///home/pi/Videos/big_buck_bunny_1080p_h264.mov...
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/home/pi/Videos/big_buck_bunny_1080p_h264.mov':
  Metadata:
    major_brand     : qt  
    minor_version   : 537199360
    compatible_brands: qt  
    creation_time   : 2005-09-28 22:15:55
  Duration: 00:00:10.01, start: 0.000000, bitrate: 1485 kb/s
    Stream #0:0(eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 128 kb/s (default)
    Metadata:
      creation_time   : 2005-09-28 22:15:55
      handler_name    : Apple Alias Data Handler
    Stream #0:1(eng): Video: h264 (Main) (avc1 / 0x31637661), yuv420p(tv, smpte170m/smpte170m/bt709), 640x480, 1349 kb/s, 29.97 fps, 29.97 tbr, 2997 tbn, 5994 tbc (default)
    Metadata:
      creation_time   : 2005-09-28 22:15:55
      handler_name    : Apple Alias Data Handler
      encoder         : H.264
12:22:53.988 VERBOSE: Copy metatada...
12:22:53.988 VERBOSE: MetaData
12:22:53.988 VERBOSE: Key: major_brand, Value: qt  .
12:22:53.988 VERBOSE: Key: minor_version, Value: 537199360.
12:22:53.988 VERBOSE: Key: compatible_brands, Value: qt  .
12:22:53.988 VERBOSE: Key: creation_time, Value: 2005-09-28 22:15:55.
12:22:53.989 VERBOSE: Initializing OMX clock...
12:22:53.989 VERBOSE: Metadata update requested.
12:22:53.995 VERBOSE: Opening video using OMX...
12:22:53.995 VERBOSE: Generating texture of size (640, 480).
12:22:53.995 INFORMATION: Instantiating texture data...
12:22:53.996 VERBOSE: Destroying QVideoSurfaceFormat.
12:22:53.996 VERBOSE: Destroying QVideoFrame.
12:22:54.002 INFORMATION: Creating EGLImageKHR...
12:22:54.002 VERBOSE: EGL image 81 created...
12:22:54.002 VERBOSE: Creating OMX_TextureData...
12:22:54.002 INFORMATION: Instantiating texture data...
12:22:54.008 INFORMATION: Creating EGLImageKHR...
12:22:54.009 VERBOSE: EGL image 82 created...
12:22:54.009 VERBOSE: Creating OMX_TextureData...
12:22:54.009 INFORMATION: Instantiating texture data...
12:22:54.015 INFORMATION: Creating EGLImageKHR...
12:22:54.015 VERBOSE: EGL image 83 created...
12:22:54.015 VERBOSE: Creating OMX_TextureData...
12:22:54.015 INFORMATION: Instantiating texture data...
12:22:54.021 INFORMATION: Creating EGLImageKHR...
12:22:54.021 VERBOSE: EGL image 84 created...
12:22:54.021 VERBOSE: Creating OMX_TextureData...
12:22:54.022 VERBOSE: Texture generated!
12:22:54.022 VERBOSE: Destroying QVideoSurfaceFormat.
12:22:54.022 VERBOSE: Destroying QVideoFrame.
12:22:54.022 VERBOSE: Setting up for new textures...
Video codec omx-h264 width 640 height 480 profile 77 fps 29.970030
12:22:54.045 VERBOSE: Opening audio using OMX...
12:22:54.045 VERBOSE: Using omx:hdmi output device...
Audio codec aac channels 2 samplerate 48000 bitspersample 16
12:22:54.077 DEBUG: State changed...
12:22:54.078 VERBOSE: Processing post play()...
12:22:54.078 DEBUG: Entering: void OpenMAXILPlayerControl::playInt().
12:22:54.078 VERBOSE: Play
12:22:54.078 VERBOSE: Cleaning textures...
12:22:54.078 VERBOSE: Entering: bool OMX_MediaProcessor::setFilenameInt(QString, OMX_TextureData*&).
12:22:54.078 INFORMATION: Cleaning up...
12:22:54.078 VERBOSE: Closing players...
12:22:54.118 VERBOSE: Metadata update requested.
12:22:54.120 VERBOSE: Freeing texture...
12:22:54.120 INFORMATION: Cleanup done.
12:22:54.120 VERBOSE: Opening /home/pi/Videos/big_buck_bunny_1080p_h264.mov...
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/home/pi/Videos/big_buck_bunny_1080p_h264.mov':
  Metadata:
    major_brand     : qt  
    minor_version   : 537199360
    compatible_brands: qt  
    creation_time   : 2005-09-28 22:15:55
  Duration: 00:00:10.01, start: 0.000000, bitrate: 1485 kb/s
    Stream #0:0(eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 128 kb/s (default)
    Metadata:
      creation_time   : 2005-09-28 22:15:55
      handler_name    : Apple Alias Data Handler
    Stream #0:1(eng)
: Video: h264 (Main) (avc1 / 0x31637661), yuv420p(tv, smpte170m/smpte170m/bt709), 640x480, 1349 kb/s, 29.97 fps, 29.97 tbr, 2997 tbn, 5994 tbc (default)
    Metadata:
      creation_time   : 2005-09-28 22:15:55
      handler_name    : Apple Alias Data Handler
      encoder         : H.264
12:22:54.189 VERBOSE: Copy metatada...
12:22:54.189 VERBOSE: MetaData
12:22:54.190 VERBOSE: Key: major_brand, Value: qt  .
12:22:54.190 VERBOSE: Key: minor_version, Value: 537199360.
12:22:54.190 VERBOSE: Key: compatible_brands, Value: qt  .
12:22:54.191 VERBOSE: Key: creation_time, Value: 2005-09-28 22:15:55.
12:22:54.191 VERBOSE: Initializing OMX clock...
12:22:54.191 VERBOSE: Metadata update requested.
12:22:54.195 VERBOSE: Opening video using OMX...
12:22:54.196 VERBOSE: Generating texture of size (640, 480).
12:22:54.196 INFORMATION: Freeing KHR image...
12:22:54.197 INFORMATION: Freeing texture...
12:22:54.197 INFORMATION: Freeing KHR image...
12:22:54.198 INFORMATION: Freeing texture...
12:22:54.198 INFORMATION: Freeing KHR image...
12:22:54.198 INFORMATION: Freeing texture...
12:22:54.199 INFORMATION: Freeing KHR image...
12:22:54.199 INFORMATION: Freeing texture...
12:22:54.200 VERBOSE: Destroying QVideoSurfaceFormat.
12:22:54.200 INFORMATION: Instantiating texture data...
12:22:54.200 VERBOSE: Destroying QVideoFrame.
12:22:54.200 VERBOSE: VideoBuffer freed.
12:22:54.207 INFORMATION: Creating EGLImageKHR...
12:22:54.207 VERBOSE: EGL image 85 created...
12:22:54.208 VERBOSE: Creating OMX_TextureData...
12:22:54.208 INFORMATION: Instantiating texture data...
12:22:54.214 INFORMATION: Creating EGLImageKHR...
12:22:54.214 VERBOSE: EGL image 86 created...
12:22:54.215 VERBOSE: Creating OMX_TextureData...
12:22:54.215 INFORMATION: Instantiating texture data...
12:22:54.221 INFORMATION: Creating EGLImageKHR...
12:22:54.221 VERBOSE: EGL image 87 created...
12:22:54.222 VERBOSE: Creating OMX_TextureData...
12:22:54.222 INFORMATION: Instantiating texture data...
12:22:54.228 INFORMATION: Creating EGLImageKHR...
12:22:54.228 VERBOSE: EGL image 88 created...
12:22:54.229 VERBOSE: Creating OMX_TextureData...
12:22:54.229 VERBOSE: Texture generated!
12:22:54.229 VERBOSE: Destroying QVideoSurfaceFormat.
12:22:54.229 VERBOSE: Destroying QVideoFrame.
12:22:54.229 VERBOSE: Setting up for new textures...
Video codec omx-h264 width 640 height 480 profile 77 fps 29.970030
12:22:54.246 VERBOSE: Opening audio using OMX...
12:22:54.246 VERBOSE: Using omx:hdmi output device...
Audio codec aac channels 2 samplerate 48000 bitspersample 16
12:22:54.276 DEBUG: State changed...
12:22:54.277 DEBUG: State changed...
12:22:54.278 VERBOSE: Starting thread.
12:22:54.278 VERBOSE: Decoding thread started.
12:22:54.282 WARNING: No decoded frame to show at all. Let' render black.
12:22:54.283 WARNING: No decoded frame to show at all. Let' render black.
V:PortSettingsChanged: 640x480@29.97 interlace:0 deinterlace:0 anaglyph:0 par:inf layer:0 alpha:255
12:22:54.308 DEBUG: bool COMXVideo::SetVideoEGL()
12:22:54.314 DEBUG: Trying to enable to output port...
12:22:54.314 VERBOSE: Creating buffers for 4 images.
12:22:54.315 INFORMATION: Buffer created 0x63ff10
12:22:54.315 INFORMATION: Buffer created 0x6402d0
12:22:54.316 INFORMATION: Buffer created 0x61a2c0
12:22:54.316 INFORMATION: Buffer created 0x622370
12:22:54.316 VERBOSE: Component renderer: 640b68.
12:22:54.322 WARNING: No decoded frame to show at all. Let' render black.
12:22:54.323 WARNING: No decoded frame to show at all. Let' render black.
12:22:54.330 WARNING: No decoded frame to show at all. Let' render black.
12:22:54.330 WARNING: No decoded frame to show at all. Let' render black.
12:22:54.376 WARNING: No decoded frame to show at all. Let' render black.
12:22:54.377 WARNING: No decoded frame to show at all. Let' render black.
12:22:54.393 WARNING: No decoded frame to show at all. Let' render black.
12:22:54.394 WARNING: No decoded frame to show at all. Let' render black.
12:22:54.409 WARNING: No decoded frame to show at all. Let' render black.
12:22:54.410 WARNING: No decoded frame to show at all. Let' render black.
12:22:54.426 WARNING: No decoded frame to show at all. Let' render black.
12:22:54.427 WARNING: No decoded frame to show at all. Let' render black.
12:22:54.442 WARNING: No decoded frame to show at all. Let' render black.
12:22:54.443 WARNING: No decoded frame to show at all. Let' render black.
12:22:54.459 WARNING: No decoded frame to show at all. Let' render black.
12:22:54.460 WARNING: No decoded frame to show at all. Let' render black.
12:22:54.476 WARNING: No decoded frame to show at all. Let' render black.
12:22:54.477 WARNING: No decoded frame to show at all. Let' render black.
12:22:54.492 WARNING: No decoded frame to show at all. Let' render black.
12:22:54.493 WARNING: No decoded frame to show at all. Let' render black.
12:22:54.509 WARNING: No decoded frame to show at all. Let' render black.
12:22:54.510 WARNING: No decoded frame to show at all. Let' render black.
12:22:54.526 WARNING: No decoded frame to show at all. Let' render black.
12:23:04.479 VERBOSE: Stopping OMX clock...
12:23:04.481 INFORMATION: Cleaning up...
12:23:04.482 VERBOSE: Closing players...
12:23:04.620 VERBOSE: Metadata update requested.
12:23:04.623 VERBOSE: Freeing texture...
12:23:04.624 INFORMATION: Cleanup done.
12:23:04.624 DEBUG: State changed...

**Comment by carlonluca** [comment]
I'll take care of this. In the meantime you can loop using the stopped signal.

**Comment by sinadogru** [comment]
Alright Thank you,

I have done like it and its working,

onStopped: {
    player.stop();
    player.play();
}

**Comment by carlonluca** [comment]
Beta 2 should fix this.
