### ISSUE TITLE
.jpg image data V-5.0.0 beta 2

### ISSUE THREAD

**Issue by sinadogru** [carlonluca/pi#37]
It seems like (if I dont miss some image packages) .jpg formatted images gives error like this,

"QML Image: Invalid image data: qrc:///assets/loby.jpg"

Here is the sample code,

    Image {
        width: 480
        height: 320
        source: "assets/loby.jpg"
    }

**Comment by sinadogru** [comment]
btw I have tried with .png and it was working

**Comment by carlonluca** [comment]
POT only decodes audio and video, not images. Images should be decoded by Qt. If you are using my build it should be using the system libjpeg. But it is not me doing it.

**Comment by sinadogru** [comment]
Thank you, you are right.

clean Rasbian image misses libjpeg.so.62 which is "libjpeg62" package. So I have downloaded and it is now working.
