### ISSUE TITLE
instantiate a MediaPlayer with 'volume: 0.0'

### ISSUE THREAD

**Issue by sinadogru** [carlonluca/pi#43]
I am trying to instantiate a MediaPlayer item with volume property setted to '0.0' but there still audio. But if I instantiate its muted property as true, then there is no volume. 

And also when I put volume to '0.0' after video start to playing, the effect of it on volume is not same as like the effect of 'muted: true', there is still little volume on.

Thank you,
Sina

**Comment by carlonluca** [comment]
You should get the fix for the issues in the next release. Please reopen if needed.

**Comment by sinadogru** [comment]
Ok thank you
