### ISSUE TITLE
[question] did you try use other frameworks?

### ISSUE THREAD

**Issue by RSATom** [carlonluca/pi#46]
like GStreamer/libvlc? If yes, by what reason (reasons) did you prefer omxplayer?

**Comment by carlonluca** [comment]
At the time I started none was providing what I needed, including omxplayer. The project uses openmax.

**Comment by RSATom** [comment]
So it's http://thebugfreeblog.blogspot.it/2013/01/custom-qml-component-for-hardware.html just outdated info? Do you use ffmpeg directly?

**Comment by carlonluca** [comment]
No, it is still valid. It says I'm leveraging code from omxplayer, properly patched and integrated. So POT uses openmax and ffmpeg directly, and includes all the related code.

**Comment by RSATom** [comment]
Understand. Is this code necessary to have hardware accelerated QML on RPi or it's only related to video playback?
