### ISSUE TITLE
palette blinking on the upper left corner

### ISSUE THREAD

**Issue by sinadogru** [carlonluca/pi#47]
I am not sure if this is the POT problem or even an issue, but there is a mini square color palette blinking on the upper left of my screen on every time a video starts. I guess it did appeared after I update my pi with rpi-update. 

Is there anyone also having this?
If yes, is there a any way to disable it?

**Comment by keytee** [comment]
Dear sinadogru,

If you are using rPI 7 inch display, it means you have low power. Try to add external power to it or a stronger 5v power supply.
Tibor

**Comment by sinadogru** [comment]
Ah keytee, Thank you so much :) 
It is solved.
Cheers,
Sina
