### ISSUE TITLE
prepare_3rdparty.sh qt_src_root

### ISSUE THREAD

**Issue by metropt** [carlonluca/pi#50]
qt_src_root in pi/piomxtextures_tools/prepare_3rdparty.sh isn't been used.

**Comment by carlonluca** [comment]
Not sure what you mean sorry.

**Comment by metropt** [comment]
```
function show_help {
	echo "Usage: prepare_3rdparty.sh <qt_src_root> pi1|pi2"
	exit 0
}
```
qt_src_root isn't been using anywhere on that file.

**Comment by carlonluca** [comment]
echo "SRC_DIR=$1" > "$THIS_DIR/../piomxtextures_qt_driver/mediaplayer/.qmake.conf"
