### ISSUE TITLE
Duration atribute is not trigerred once changed

### ISSUE THREAD

**Issue by alvarolaracano** [carlonluca/pi#52]
I have just made a simple program using PiomxTextures. I need to know current media duration in order to trigger an event and this attribute changes asynchronously, so in desktop mode i am using onDurationChanged to dispatch event. But this is no longer working in Piomxtextures.

 
MediaPlayer {
        id: player
        autoPlay: false
        onDurationChanged: {
            console.log('Duration changed: ' + player.duration)
                console.log('Finish early')
                timer.interval = (player.duration - 1200)
                timer.start()
    }

**Comment by atr0n** [comment]
Maybe you can try to get the duration from metadata and then, make you own countdown counter.

**Comment by alvarolaracano** [comment]
In fact i need to trigger an event when the duration metadata is loaded, and i am achieving this using onDurationChanged in desktop mode.

**Comment by carlonluca** [comment]
Build 5.2.1 should include the signal. Reopen if needed.
